english/urls.py
from django.urls import path
from .views import (
    HomeView, PublishWordBooksListView, TypingWordsView, WordBooksListView, WordsListView,
    delete_word, delete_wordbook, update_wordbook_publish
)

app_name = 'english'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('wordbooks/', WordBooksListView.as_view(), name='wordbooks'),
    path('update_wordbook_publish/', update_wordbook_publish, name='update_wordbook_publish'),
    path('words/<int:pk>', WordsListView.as_view(), name='words'),
    path('typing/<int:pk>', TypingWordsView.as_view(), name='typing'),
    path('publish_wordbooks/', PublishWordBooksListView.as_view(), name='publish_wordbooks'),
    path('delete_wordbook/<int:pk>', delete_wordbook, name='delete_wordbook'),
    path('delete_word/<int:pk>_<int:wordbook_id>', delete_word, name='delete_word'),
]

typing_words/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('english.urls')),
]

english/models.py
from django.db import models
from django.utils import timezone
from accounts.models import Users


class WordBooks(models.Model):
    user = models.ForeignKey(
        Users, on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    publish = models.BooleanField(default=False)
    create_at = models.DateTimeField(default=timezone.now)
    update_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'wordbooks'

    def __str__(self):
        return self.name

    
class Words(models.Model):
    wordbook = models.ForeignKey(
        WordBooks, on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    create_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = 'words'

    def __str__(self):
        return self.name

english/forms.py
from django import forms
from django.forms.widgets import TextInput
from .models import WordBooks, Words


class WordBooksForm(forms.ModelForm):
    name = forms.CharField(
        label='単語帳名',
        widget=forms.TextInput(
            attrs={
                'class': 'large-input',
                'placeholder': '単語帳名',
                'autocomplete': 'off'
            }
        )
    )
    description = forms.CharField(
        label='説明',
        widget=forms.TextInput(
            attrs={
                'class': 'large-input',
                'placeholder': '説明',
                'autocomplete': 'off'
            }
        )
    )
    publish = forms.BooleanField(label='公開する', required=False)

    class Meta:
        model = WordBooks
        fields = ['name', 'description', 'publish']

    def save(self):
        workbook = super().save(commit=False)
        # ここで参照関係のユーザを渡す
        workbook.user = self.user
        workbook.save()
        return workbook

    
class WordsForm(forms.ModelForm):
    name = forms.CharField(
        label='単語',
        widget=forms.TextInput(
            attrs={
                'class': 'large-input',
                'placeholder': '単語',
                'autocomplete': 'off'
            }
        )
    )
    description = forms.CharField(
        label='意味',
        widget=forms.TextInput(
            attrs={
                'class': 'large-input',
                'placeholder': '意味',
                'autocomplete': 'off'
            }
        )
    )

    class Meta:
        model = Words
        fields = ['name', 'description']

    def save(self):
        word = super().save(commit=False)
        word.wordbook = self.wordbook
        word.save()
        return word

english/views.py
from django.http.response import JsonResponse
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import ModelFormMixin
from .models import WordBooks, Words
from .forms import WordBooksForm, WordsForm
import os


class HomeView(TemplateView): 
    template_name = os.path.join('english', 'home.html')


class WordBooksListView(LoginRequiredMixin, ListView, ModelFormMixin):
    model = WordBooks
    form_class = WordBooksForm
    paginate_by = 5
    template_name = os.path.join('english', 'wordbooks.html')
    success_url = reverse_lazy('english:wordbooks')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user).order_by('-update_at')

    def get(self, request, *args, **kwargs):
        # ModelFormMixinには↓が必要
        self.object = None
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        self.object_list = self.get_queryset()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        # formに必要な値を渡して、フォームクラス内のsave()でモデルに追加する
        form.user = self.request.user
        return super().form_valid(form)


class WordsListView(LoginRequiredMixin, ListView, ModelFormMixin):
    model = Words
    paginate_by = 20
    template_name = os.path.join('english', 'words.html')
    form_class = WordsForm

    def get_success_url(self):
        # get_success_urlはurlを返さないとだめ
        return reverse_lazy('english:words', kwargs={'pk':self.kwargs.get('pk')})

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset()
        return queryset.filter(wordbook=self.kwargs.get('pk')).order_by('-create_at')

    def get_context_data(self, **kwargs):
        self.object = None
        context_data = super().get_context_data(**kwargs)
        context_data['wordbook'] = WordBooks.objects.filter(pk=self.kwargs.get('pk')).first()
        # 総登録単語数表示用
        context_data['count'] = Words.objects.filter(wordbook=self.kwargs.get('pk')).all().count()
        return context_data

    def get(self, request, *args, **kwargs):
        if not self.check_owner_user(kwargs.get('pk'), request.user):
            return redirect('english:wordbooks')  
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        context_data = self.get_context_data()
        form.wordbook = context_data['wordbook']
        return super().form_valid(form)

    # 単語帳の作成ユーザーか判定
    def check_owner_user(self, wordbook_id, user):
        wordbook = WordBooks.objects.filter(pk=wordbook_id, user=user).all()
        if not wordbook:
            return False
        return True
        

class TypingWordsView(DetailView):
    """タイピングゲームのビュー。

    Wordbooksに紐づく単語を、タイピングゲームとして遊べる

    """
    model = WordBooks
    template_name = os.path.join('english', 'typing.html')

    def get(self, request, *args, **kwargs):
        """ゲットアクション

        公開・非公開かかわらず、タイピングゲームのビューは一つだけなので
        Wordbooksの公開設定、リクエストユーザーとWordbooksの作者の比較で
        GETリクエストを変える。

        Returns:
            HttpResponse: 公開設定 → ok
            HttpResponse: 非公開 and リクエストユーザ == Wordbooks作者 → ok
            HttpResponse: 非公開 and リクエストユーザ != Wordbooks作者 → redirect
        """
        user = request.user
        wordbook = WordBooks.objects.filter(pk=kwargs.get('pk')).first()
        if wordbook.publish:
            # 公開設定されているwordbookの場合
            return super().get(request, *args, **kwargs)
        else:
            if user == wordbook.user:
                # 公開設定されていないけど、リクエストユーザと作者が同じ
                return super().get(request, *args, **kwargs)
            else:
                # 公開設定されていなくて、リクエストユーザと作者が違う
                return redirect('english:publish_wordbooks')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['wordbook'] = WordBooks.objects.filter(pk=self.kwargs.get('pk')).values('id', 'user', 'name', 'description').first()
        # 単語を並べ替えて入れる
        words = Words.objects.filter(wordbook=self.kwargs.get('pk')).order_by('?')
        context_data['words'] = list(words.values('id', 'wordbook', 'name', 'description'))

        return context_data
        

class PublishWordBooksListView(ListView):
    model = WordBooks
    paginate_by = 5
    template_name = os.path.join('english', 'publish_wordbooks.html')

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset()
        return queryset.filter(publish=True).order_by('-create_at')


@login_required
def update_wordbook_publish(request):
    # words内のWordBookの公開非公開
    if request.is_ajax:
        wordbook_id = request.POST.get('wordbook_id')
        publish = True if request.POST.get('publish') == 'true' else False
        wordbook = get_object_or_404(WordBooks, id=wordbook_id)
        wordbook.publish = publish
        wordbook.save()
        if publish:
            return JsonResponse({'message': '公開に設定しました'})
        else:
            return JsonResponse({'message': '非公開に設定しました'})


@login_required
def delete_wordbook(request, pk):
    # WordBookの削除
    wordbook = WordBooks.objects.filter(pk=pk, user=request.user).first()
    if wordbook:
        wordbook.delete()
    return redirect('english:wordbooks')

@login_required
def delete_word(request, pk, wordbook_id):
    word = Words.objects.filter(pk=pk, wordbook=wordbook_id).first()
    if not word:
        return redirect('english:wordbooks')
    if word.wordbook.user == request.user:
        # wordの作成者とリクエストユーザが同じ場合のみ
        word.delete()
    return redirect('english:words', wordbook_id)

templates/english/home.html
{% extends 'base.html' %}
{% block content %}
<div class="title">
    <h1>Englishのホームです</h1>
</div>
{% endblock content %}

templates/english/publish_wordbooks.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="title">
    <h1>みんなの単語帳</h1>
</div>
<div class="main">
    <div class="card-list">
        <div class="card-links">
            {% if page_obj.has_previous %}
                <div>
                    <a href="?page=1">&laquo; first</a>
                </div>
                <div>
                    <a href="?page={{ page_obj.previous_page_number }}">prev</a>
                </div>
            {% else %}
                <div></div>
                <div></div>
            {% endif %}

            <div>
                <span class="current">
                    Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                </span>
            </div>

            {% if page_obj.has_next %}
                <div>
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                </div>
                <div>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                </div>
            {% else %}
                <div></div>
                <div></div>
            {% endif %}
        </div>
        {% for wordbook in object_list %}
        <div class="card">
            <nav class="card-nav">
                <ul class="card-nav-menu">
                    <a class="red-link" href="{% url 'english:typing' wordbook.id %}"><i class="fas fa-keyboard"></i> タイピング</a>
                </ul>
            </nav>
            <div class="card-body">
                <h1>{{ wordbook.name }}</h1>
                <p>{{ wordbook.description }}</p>
                <p>by {{ wordbook.user.username }}</p>
            </div>
            <div class="card-footer">
                <small>更新日:{{ wordbook.update_at }}</small>
            </div>
        </div>
        {% endfor %}
    </dv>
</div>
{% endblock content %}

templates/english/typing.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="title">
    <h1>{{ wordbook.name }}</h1>
</div>
<div class="main">
    <div id="typing" class="typing">
        <h1 id="description"></h1>
        <p id="name"></p>
        <div id="score">
            <p>成功: <span id="success"></span></p>
            <p>失敗: <span id="failed"></span></p>
        </div>
    </div>
</div>
<input type="hidden" name="csrfToken" value="{{ csrf_token }}">
<script>
var words = {{ words|safe }};
var wordbook = {{ wordbook|safe }};
</script>
<script type="text/javascript" src="{% static 'js/game/tap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/game/typing.js' %}"></script>
<script type="text/javascript" src="{% static 'js/game/main.js' %}"></script>
{% endblock %}

templates/english/wordbooks.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="title">
    <h1>あなたの単語帳</h1>
</div>
<div class="main">
    <div class="card-form">
        <h2>新しい単語帳を作る</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.name }}
            {{ form.description }}
            <div>
                <div class="toggle">
                    {{ form.publish }}
                    <label for="id_publish"></label>
                    <p>公開する</p>
                </div>
                <input class="red-btn large-btn" type="submit" value="作成">
            </div>
        </form>
    </div>
    <div class="card-links">
        {% if page_obj.has_previous %}
            <div>
                <a href="?page=1">&laquo; first</a>
            </div>
            <div>
                <a href="?page={{ page_obj.previous_page_number }}">prev</a>
            </div>
        {% else %}
            <div></div>
            <div></div>
        {% endif %}

        <div>
            <span class="current">
                Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
            </span>
        </div>

        {% if page_obj.has_next %}
            <div>
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            </div>
            <div>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            </div>
        {% else %}
            <div></div>
            <div></div>
        {% endif %}
    </div>
    <div class="card-list">
        {% for wordbook in object_list %}
        <div class="card">
            <nav class="card-nav">
                <ul class="card-nav-menu">
                    <li class="card-nav-menu-item">
                        <a class="red-link" href="{% url 'english:typing' wordbook.id %}"><i class="fas fa-keyboard"></i> タイピング</a>
                    </li>
                    <li class="card-nav-menu-item">
                        <a class="red-link" href="{% url 'english:words' wordbook.id %}"><i class="fas fa-edit"></i> 編集</a>
                    </li>
                </ul>
            </nav>
            <div class="card-body">
                {% comment %} <h3>{{ wordbook.name }}</h3> {% endcomment %}
                <h1>{{ wordbook.name }}</h1>
                <p>{{ wordbook.description }}</p>
            </div>
            <div class="card-footer">
                <small>更新日:{{ wordbook.update_at }}</small>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/english/words.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="title">
    <h1>単語帳の編集</h1>
</div>
<div class="main">
    <div class="words-form">
        <div class="words-btn">
            <a href="{% url 'english:wordbooks' %}" id="back" class="red-link"><i class="fas fa-arrow-left"></i></a>
            <a href="{% url 'english:delete_wordbook' wordbook.id %}" id="delete" class="grey-link"><i class="fas fa-trash-alt"></i></a>
        </div>
        <div class="words-title">
            <div>
                <h1>{{ wordbook.name }}</h1>
                <p>{{ wordbook.description }}</p>
                <p>登録単語数: {{ count }}個</p>
                <div class="toggle">
                    <input id="update_wordbook_publish" type="checkbox" name="publish" {% if wordbook.publish %}checked{% endif %}>
                    <label for="update_wordbook_publish"></label>
                    <p>公開する</p>
                </div>
                <input type="hidden" name="csrfToken" value={{ csrf_token }}>
            </div>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ form.name }}
            {{ form.description }}
            <div>
                <input class="red-btn large-btn" type="submit" value="登録">
            </div>
        </form>
    </div>
    <div class="words-links">
        {% if page_obj.has_previous %}
            <div>
                <a href="?page=1">&laquo; first</a>
            </div>
            <div>
                <a href="?page={{ page_obj.previous_page_number }}">prev</a>
            </div>
        {% else %}
            <div></div>
            <div></div>
        {% endif %}

        <div>
            <span class="current">
                Page {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
            </span>
        </div>

        {% if page_obj.has_next %}
            <div>
                <a href="?page={{ page_obj.next_page_number }}">next</a>
            </div>
            <div>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            </div>
        {% else %}
            <div></div>
            <div></div>
        {% endif %}
    </div>
    <div class="words-list">
        <div class="words-table">
            <dl class="words-table-head">
                <dt>
                    <span>単語</span>
                </dt>
                <dd>
                    <span>意味</span>
                </dd>
                <dd>
                </dd>
            </dl>
            {% if object_list %}
                {% for word in object_list %}
                    <dl class="words-table-row">
                        <dt><span>{{ word.name }}</span></dt>
                        <dd><span>{{ word.description }}</span></dd>
                        <dd><a href="{% url 'english:delete_word' word.id wordbook.id %}" class="grey-link"><i class="fas fa-trash-alt"></i></a></dd>
                    </dl>
                {% endfor %}
            {% else %}
                <dl class="words-table-row">
                    <dt><span></span></dt>
                    <dd><span></span></dd>
                    <dd></dd>
                </dl>
            {% endif %}
        </div>
    </div>
</div>
<script>
$('#update_wordbook_publish').click(function(){
    var publish = null;
    if ($('#update_wordbook_publish').prop('checked')) {
        publish = true;
    } else {
        publish = false;
    }
    var token = $('input[name=csrfToken]').attr('value');
    $.ajaxSetup({
        beforeSend: function(xhr){
            xhr.setRequestHeader('X-CSRFToken', token);
        }
    })
    $.ajax({
        url: "{% url 'english:update_wordbook_publish' %}",
        type: 'POST',
        data: {wordbook_id: '{{ wordbook.id }}', publish: publish},
        dataType: 'json',
        success:function(json){
            if(json.message){
                console.log(json.message);
            }
        }
    })
});
</script>
{% endblock content %}