accounts/urls.py
from .views import HomeView, LogoutView, PasswordResetView, RegistComplete, user_login, user_regist
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    # path('home/', HomeView.as_view(), name='home'),
    path('regist/', user_regist, name='regist'),
    path('password_reset/<uuid:token>', PasswordResetView.as_view(), name='password_reset'),
    path('login/', user_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('complete/', RegistComplete.as_view(), name='regist_complete'),
]

english/urls.py
from django.urls import path
from .views import (
    HomeView, PublishWordBooksListView, TypingWordsView, WordBooksListView, WordsListView,
    delete_word, delete_wordbook, update_wordbook_publish
)

app_name = 'english'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('wordbooks/', WordBooksListView.as_view(), name='wordbooks'),
    path('update_wordbook_publish/', update_wordbook_publish, name='update_wordbook_publish'),
    path('words/<int:pk>', WordsListView.as_view(), name='words'),
    path('typing/<int:pk>', TypingWordsView.as_view(), name='typing'),
    path('publish_wordbooks/', PublishWordBooksListView.as_view(), name='publish_wordbooks'),
    path('delete_wordbook/<int:pk>', delete_wordbook, name='delete_wordbook'),
    path('delete_word/<int:pk>_<int:wordbook_id>', delete_word, name='delete_word'),
]

typing_words/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('english.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>テストサイト</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
    {% if not user.is_authenticated %}
        <link rel="stylesheet" href="{% static 'css/modal/modal.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'css/english/english.css' %}">
    <link rel="stylesheet" href="{% static 'css/accounts/accounts.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
</head>
<body>
    <nav class="nav">
        <h1 class="title"><a class="red-link" href="{% url 'english:home' %}">TYEPING</a></h1>
        <ul class="nav-menu">
            <li class="nav-menu-item"><a class="red-link" href="{% url 'english:home' %}"><i class="fas fa-home"></i> ホーム</a></li>
            <li class="nav-menu-item"><a class="red-link" href="{% url 'english:publish_wordbooks' %}"><i class="fas fa-book-reader"></i> みんなの単語帳</a></li>
            {% if user.is_authenticated %}
            <li class="nav-menu-item"><a class="red-link" href="{% url 'english:wordbooks' %}" class="navbar-brand"><i class="fas fa-book"></i> 単語帳</a></li>
            <li class="nav-menu-item"><a class="red-link" href="{% url 'accounts:logout' %}" class="navbar-brand"><i class="fas fa-sign-out-alt"></i> ログアウト</a></li>
            {% else %}
            <li class="nav-menu-item"><a class="red-link" href="#" class="navbar-brand" id="open-regist"><i class="fas fa-user-plus"></i> 新規登録</a></li>
            <li class="nav-menu-item"><a class="red-link" href="#" class="navbar-brand" id="open-login"><i class="fas fa-sign-in-alt"></i> ログイン</a></li>
            {% endif %}
        </ul>
    </nav>
    <main class="content">
        {% block content %}
        {% endblock content %}
    </main>
    {% if not user.is_authenticated %}
        <div id="mask-login" class="hidden"></div>
        <div id="modal-login" class="hidden">
            <div class="modal-body">
                <h1>ログイン</h1>
                <form id="form-login" action="" method="post" novalidate>
                    {% csrf_token %}
                    <input class="large-input" type="text" name="login-username" id="login-username" placeholder="メールアドレス">
                    <input class="large-input" type="password" name="login-password" id="login-password" placeholder="パスワード">
                    <input class="large-submit" type="submit" value="ログイン">
                </form>
            </div>
        </div>
        <div id="mask-regist" class="hidden"></div>
        <div id="modal-regist" class="hidden">
            <div class="modal-body">
                <h1>新規登録</h1>
                <form id="form-regist" action="" method="post" novalidate>
                    {% csrf_token %}
                    <input class="large-input" type="text" name="username" placeholder="ユーザ名">
                    <input class="large-input" type="email" name="email" placeholder="メールアドレス">
                    <input class="large-submit" type="submit" value="登録">
                </form>
            </div>
        </div>
        <div id="mask-message" class="hidden"></div>
        <div id="modal-message" class="hidden">
            <div class="modal-body">
                <div id="message-body"></div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        <script>
            var loginUrl = "{% url 'accounts:login' %}"
            var registUrl = "{% url 'accounts:regist' %}"
        </script>
        <script type="text/javascript" src="{% static 'js/modal/main.js' %}"></script>
    {% endif %}
</body>
</html>